<!DOCTYPE html>
<html lang="fr-FR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="profile" href="http://gmpg.org/xfn/11">
    <title>Iorem ipsum</title>
    <link rel="dns-prefetch" href="//fonts.googleapis.com">
    <link rel="dns-prefetch" href="//s.w.org">
   

    <link rel="stylesheet" id="onepress-bootstrap-css" href="static/css/bootstrap.min.css" type="text/css" media="all">
    <link rel="stylesheet" id="onepress-style-css" href="static/css/style.css" type="text/css" media="all">
    <style id="onepress-style-inline-css" type="text/css">
        #main .video-section section.hero-slideshow-wrapper {
            background: transparent
        }
        
        .hero-slideshow-wrapper:after {
            position: absolute;
            top: 0px;
            left: 0px;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0);
            display: block;
            content: ""
        }
        
        .body-desktop .parallax-hero .hero-slideshow-wrapper:after {
            display: none!important
        }
        
        #parallax-hero>.parallax-bg::before {
            background-color: rgba(0, 0, 0, 0);
            opacity: 1
        }
        
        .body-desktop .parallax-hero .hero-slideshow-wrapper:after {
            display: none!important
        }
        
        .gallery-carousel .g-item {
            padding: 0px 1px
        }
        
        .gallery-carousel {
            margin-left: -1px;
            margin-right: -1px
        }
        
        .gallery-grid .g-item,
        .gallery-masonry .g-item .inner {
            padding: 1px
        }
        
        .gallery-grid,
        .gallery-masonry {
            margin: -1px
        }
    </style>
    <script type="text/javascript">
        /* <![CDATA[ */
        var onepress_js_settings = {
            "onepress_disable_animation": "",
            "onepress_disable_sticky_header": "",
            "onepress_vertical_align_menu": "",
            "hero_animation": "flipInX",
            "hero_speed": "2000",
            "hero_fade": "750",
            "hero_duration": "2000",
            "is_home": "",
            "gallery_enable": ""
        };
        /* ]]> */
    </script>
    <script type="text/javascript" src="static/js/jquery.js"></script>
    <script type="text/javascript" src="static/js/vendor.bundle.js"></script>
    <script type="text/javascript" src="static/js/front.bundle.js"></script>
    <meta name="generator">
    <!-- Custom CSS -->
    <style>
        .page-header {
            padding: 0px 0px;
            border-top: 1px solid #e9e9e9;
            background: #f8f9f9;
            border-bottom: 1px solid #e9e9e9;
        }
        
        element.style {}
        
        style.css?ver=4.8.3:614 #primary {
            padding-bottom: 40px;
            padding-top: 20px;
        }
        
        h3 {
            font-size: 20px;
            font-size: 1rem;
            font-weight: 600;
            text-align: center;
        }
        
        .page-header .entry-title,
        .page-header .page-title {
            margin-bottom: 0px;
            font-size: 20px;
            font-weight: 600;
            letter-spacing: 1px;
            text-transform: uppercase;
            text-align: center;
        }
        
        .col-sm-6 {
            -webkit-box-flex: 0;
            -webkit-flex: 0 0 50%;
            -ms-flex: 0 0 50%;
            flex: 0 0 100%;
            max-width: 100%;
        }
        
        h3 {
            font-size: 20px;
            font-size: 1rem;
            font-weight: 700;
            text-align: LEFT;
        }
    </style>
    <!-- Generated by https://wordpress.org/plugins/theme-junkie-custom-css/ -->
    <link rel="icon" href="./static/images/icon32.png" sizes="32x32">
    <link rel="icon" href="./static/images/icon192.png" sizes="192x192">
    <link rel="apple-touch-icon-precomposed" href="./static/images/icon180.png">
    <meta name="msapplication-TileImage" content="./static/images/icon270.png">
    <style type="text/css" id="wp-custom-css">
        /*
Vous pouvez ajouter du CSS personnalisé ici.

Cliquez sur l’icône d’aide ci-dessus pour en savoir plus.
*/
    </style>
</head>

<body class="home page-template page-template-template-frontpage page-template-template-frontpage-php page page-id-1251 wp-custom-logo vcwb vcwb-ver-1.8 group-blog sticky-header no-header-transparent body-desktop">
	<a href="https://www.google.fr">
		<img src="./static/images/biosiegel.png" class="onScreenBtn">
	</a>
    <div id="page" class="hfeed site">
        <a class="skip-link screen-reader-text" href="#content">Aller au contenu</a>
        <div class="site-header-wrapper is-fixed">
            <header id="masthead" class="site-header header-fixed" role="banner" style="top: 0px;">
                
				<div class="container" >
                    <div class="site-branding">
                      <div class="site-brand-inner has-logo-img no-desc">
                            <div>
                                <a href="index.html" class="headline" rel="home" itemprop="url">Head Line</a>
                            </div>
                        </div>
                    </div>
                    <!-- .site-branding -->

                    <div class="header-right-wrapper">
                        <a href="#0" id="nav-toggle">Menu<span></span></a>
					
                        <nav id="site-navigation" class="main-navigation" role="navigation">
                            <ul class="onepress-menu">
                                <li id="menu-item-1510" class="menu-item menu-item-type-custom menu-item-object-custom current-menu-item current_page_item menu-item-home menu-item-1510"><a href="#text">Link 1</a></li>
                                <li id="menu-item-1515" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1515"><a href="./postpage.html">Link 2</a></li>
                                
                              <li id="menu-item-1522" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1522"><a href="./print.php">Link 3</a></li>
                            </ul>
                        </nav>
                        <!-- #site-navigation -->
                    </div>
                </div>
				<div style="border-bottom: 2px solid rgb(141, 141, 141);margin-top: 80px;margin-left: 10%;margin-right: 10%;">
            	</div>
			</header>
        </div>
        <!-- #masthead -->

        <div id="content" class="site-content">
            <main id="main" class="site-main" role="main">
                <section id="hero" img="\static\images\banner.png" class="hero-slideshow-wrapper hero-slideshow-normal loaded" style="position: relative; z-index: 0; background: none; padding-top:4%">
					
					
					<div style="text-align: center">
						<img src="./static/images/banner.png" style="width: 80%; height: auto;">
						
                    </div>
					
					<div class="container" style="padding-top: 4%; padding-bottom: 4%; width: 80%;column-width:600px;column-count:auto; column-gap:5%;">
						<div class="text" id="text">
						   <?php 
							require 'config.php';
							require 'mysql.class.php';
							DB::connect();
							mysqli_query(DB::$con,'set names utf8');

							$gb_select_sql_num = 'SELECT num FROM ' . GB_TABLE_NUM;
							$sql_select_result_num = mysqli_query(DB::$con,$gb_select_sql_num);
							$num = mysqli_fetch_array($sql_select_result_num)[0];
							if ($num % 15 == 0) echo "<h1>Three-Five<h1> ";
							else if ($num % 3 == 0) echo "<h1>Three<h1> ";
							else if ($num % 5 == 0) echo "<h1>Five<h1> ";
							else echo "<h1>{$num}<h1> ";
							if ($num>0)
								$gb_update_sql_num = 'UPDATE num SET num=num-1;';
							else $gb_update_sql_num = 'UPDATE num SET num=100;';
							//echo "<p>{$gb_update_sql_num}<p> ";
							mysqli_query(DB::$con, $gb_update_sql_num);
							DB::close();
							?>
					</div>
                    </div>
                    
                </section>
            </main>
            <!-- #main -->
        </div>
        <!-- #content -->

        <footer id="colophon" class="site-footer" role="contentinfo">

            <div class="site-info">
				<div style="border-bottom: 2px solid rgb(141, 141, 141);margin-top: 0px;margin-left: 10%;margin-right: 10%;border-bottom-width: 0px;border-top-width: 2px;border-top-style: solid;"></div>
				<br>
                <div class="container">
                    © lorem ipsum 2019                  
                    <br>
				</div>
			</div>
            <!-- .site-info -->

        </footer>
        <!-- #colophon -->
    </div>
    <!-- #page -->

    <script type="text/javascript" src="static/js/scripts.js"></script>
    <script type="text/javascript" src="static/js/plugins.js"></script>
    <script type="text/javascript" src="static/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="static/js/theme.js"></script>

</body>

</html>